// AUTO-GENERATED by website/scripts/sync_content_from_game.py.
// Do not edit by hand — re-run the script after changing pack JSONs.

export type Rarity = 'common' | 'rare' | 'epic' | 'legendary';

export interface Squishy {
  id: string;
  name: string;
  rarity: Rarity;
  packId: string;
  packSlug: string;
  packName: string;
  sprite: string;
  thumbnail: string;
  themeTag: string;
  behaviorProfile?: string | null;
  searchTags: string[];
}

export interface PackSummary {
  id: string;
  slug: string;
  displayName: string;
  blurb: string;
  accent: string;
  accentDark: string;
  emoji: string;
  counts: { common: number; rare: number; epic: number; legendary: number };
  legendaryName: string | null;
  totalCount: number;
}

export const squishies: Squishy[] = [
  {
    "id": "squishkin",
    "name": "Squishkin",
    "rarity": "common",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/squishkin.png",
    "thumbnail": "/thumbnails/squishkin_thumb.png",
    "themeTag": "blind_box_vibe",
    "behaviorProfile": null,
    "searchTags": [
      "creepy cute",
      "monster",
      "blind box",
      "weird"
    ]
  },
  {
    "id": "snagglet",
    "name": "Snagglet",
    "rarity": "rare",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/snagglet.png",
    "thumbnail": "/thumbnails/snagglet_thumb.png",
    "themeTag": "snaggletooth",
    "behaviorProfile": null,
    "searchTags": [
      "fang",
      "creepy",
      "cute",
      "spooky"
    ]
  },
  {
    "id": "gloomp",
    "name": "Gloomp",
    "rarity": "epic",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/gloomp.png",
    "thumbnail": "/thumbnails/gloomp_thumb.png",
    "themeTag": "mischievous_blob",
    "behaviorProfile": null,
    "searchTags": [
      "gremlin",
      "weird",
      "blob",
      "cute monster"
    ]
  },
  {
    "id": "blushy_bun_bunny",
    "name": "Blushy Bun Bunny",
    "rarity": "common",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/blushy_bun_bunny.png",
    "thumbnail": "/thumbnails/blushy_bun_bunny_thumb.png",
    "themeTag": "bunny",
    "behaviorProfile": "creature",
    "searchTags": [
      "bunny",
      "creature"
    ]
  },
  {
    "id": "squish_bat",
    "name": "Squish Bat",
    "rarity": "common",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/squish_bat.png",
    "thumbnail": "/thumbnails/squish_bat_thumb.png",
    "themeTag": "bat",
    "behaviorProfile": "creature",
    "searchTags": [
      "bat",
      "creepy_cute"
    ]
  },
  {
    "id": "puff_ghost",
    "name": "Puff Ghost",
    "rarity": "common",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/puff_ghost.png",
    "thumbnail": "/thumbnails/puff_ghost_thumb.png",
    "themeTag": "ghost",
    "behaviorProfile": "creature",
    "searchTags": [
      "ghost",
      "spooky"
    ]
  },
  {
    "id": "wobble_kitty",
    "name": "Wobble Kitty",
    "rarity": "common",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/wobble_kitty.png",
    "thumbnail": "/thumbnails/wobble_kitty_thumb.png",
    "themeTag": "cat",
    "behaviorProfile": "creature",
    "searchTags": [
      "cat",
      "kitty"
    ]
  },
  {
    "id": "tiny_blob_monster",
    "name": "Tiny Blob Monster",
    "rarity": "common",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/tiny_blob_monster.png",
    "thumbnail": "/thumbnails/tiny_blob_monster_thumb.png",
    "themeTag": "blob_monster",
    "behaviorProfile": "creature",
    "searchTags": [
      "monster",
      "blob"
    ]
  },
  {
    "id": "soft_fang_critter",
    "name": "Soft Fang Critter",
    "rarity": "common",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/soft_fang_critter.png",
    "thumbnail": "/thumbnails/soft_fang_critter_thumb.png",
    "themeTag": "fang",
    "behaviorProfile": "creature",
    "searchTags": [
      "fang",
      "critter"
    ]
  },
  {
    "id": "sleepy_slime_pet",
    "name": "Sleepy Slime Pet",
    "rarity": "common",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/sleepy_slime_pet.png",
    "thumbnail": "/thumbnails/sleepy_slime_pet_thumb.png",
    "themeTag": "slime_pet",
    "behaviorProfile": "creature",
    "searchTags": [
      "slime",
      "sleepy"
    ]
  },
  {
    "id": "star_eyed_bunny",
    "name": "Star-Eyed Bunny",
    "rarity": "rare",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/star_eyed_bunny.png",
    "thumbnail": "/thumbnails/star_eyed_bunny_thumb.png",
    "themeTag": "star_bunny",
    "behaviorProfile": "creature",
    "searchTags": [
      "bunny",
      "star",
      "rare"
    ]
  },
  {
    "id": "moon_bat_blob",
    "name": "Moon Bat Blob",
    "rarity": "rare",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/moon_bat_blob.png",
    "thumbnail": "/thumbnails/moon_bat_blob_thumb.png",
    "themeTag": "moon_bat",
    "behaviorProfile": "creature",
    "searchTags": [
      "moon",
      "bat",
      "rare"
    ]
  },
  {
    "id": "glow_ghost_puff",
    "name": "Glow Ghost Puff",
    "rarity": "rare",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/glow_ghost_puff.png",
    "thumbnail": "/thumbnails/glow_ghost_puff_thumb.png",
    "themeTag": "glow_ghost",
    "behaviorProfile": "creature",
    "searchTags": [
      "ghost",
      "glow",
      "rare"
    ]
  },
  {
    "id": "dream_eater_squish",
    "name": "Dream Eater Squish",
    "rarity": "epic",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/dream_eater_squish.png",
    "thumbnail": "/thumbnails/dream_eater_squish_thumb.png",
    "themeTag": "dream_eater",
    "behaviorProfile": "creature",
    "searchTags": [
      "dream_eater",
      "epic"
    ]
  },
  {
    "id": "arcane_wobble_kitty",
    "name": "Arcane Wobble Kitty",
    "rarity": "epic",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/arcane_wobble_kitty.png",
    "thumbnail": "/thumbnails/arcane_wobble_kitty_thumb.png",
    "themeTag": "arcane_kitty",
    "behaviorProfile": "creature",
    "searchTags": [
      "arcane",
      "cat",
      "epic"
    ]
  },
  {
    "id": "mythic_plush_familiar",
    "name": "Mythic Plush Familiar",
    "rarity": "legendary",
    "packId": "creepy_cute_pack_01",
    "packSlug": "creepy-cute-creatures",
    "packName": "Creepy-Cute Creatures",
    "sprite": "/sprites/mythic_plush_familiar.png",
    "thumbnail": "/thumbnails/mythic_plush_familiar_thumb.png",
    "themeTag": "legendary_familiar",
    "behaviorProfile": "creature",
    "searchTags": [
      "legendary",
      "familiar",
      "legendary"
    ]
  },
  {
    "id": "slimeorb",
    "name": "SlimeOrb",
    "rarity": "common",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/slimeorb.png",
    "thumbnail": "/thumbnails/slimeorb_thumb.png",
    "themeTag": "anti_stress",
    "behaviorProfile": null,
    "searchTags": [
      "stress ball",
      "antistress",
      "fidget",
      "satisfying"
    ]
  },
  {
    "id": "goodrop",
    "name": "GooDrop",
    "rarity": "rare",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/goodrop.png",
    "thumbnail": "/thumbnails/goodrop_thumb.png",
    "themeTag": "slime_pod",
    "behaviorProfile": null,
    "searchTags": [
      "slime",
      "asmr",
      "goo",
      "pop"
    ]
  },
  {
    "id": "popzee",
    "name": "Popzee",
    "rarity": "common",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/popzee.png",
    "thumbnail": "/thumbnails/popzee_thumb.png",
    "themeTag": "pop_pod",
    "behaviorProfile": null,
    "searchTags": [
      "bubble",
      "pop",
      "fidget",
      "asmr"
    ]
  },
  {
    "id": "bubble_blob",
    "name": "Bubble Blob",
    "rarity": "common",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/bubble_blob.png",
    "thumbnail": "/thumbnails/bubble_blob_thumb.png",
    "themeTag": "bubble",
    "behaviorProfile": "goo_ball",
    "searchTags": [
      "bubble",
      "fidget"
    ]
  },
  {
    "id": "stretch_cube",
    "name": "Stretch Cube",
    "rarity": "common",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/stretch_cube.png",
    "thumbnail": "/thumbnails/stretch_cube_thumb.png",
    "themeTag": "stretch",
    "behaviorProfile": "stress_ball",
    "searchTags": [
      "stretch",
      "cube",
      "fidget"
    ]
  },
  {
    "id": "soft_stress_orb",
    "name": "Soft Stress Orb",
    "rarity": "common",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/soft_stress_orb.png",
    "thumbnail": "/thumbnails/soft_stress_orb_thumb.png",
    "themeTag": "stress_ball",
    "behaviorProfile": "stress_ball",
    "searchTags": [
      "stress",
      "ball",
      "fidget"
    ]
  },
  {
    "id": "jelly_pad",
    "name": "Jelly Pad",
    "rarity": "common",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/jelly_pad.png",
    "thumbnail": "/thumbnails/jelly_pad_thumb.png",
    "themeTag": "jelly_pad",
    "behaviorProfile": "jelly_cube",
    "searchTags": [
      "jelly",
      "pad"
    ]
  },
  {
    "id": "sticky_pop_ball",
    "name": "Sticky Pop Ball",
    "rarity": "common",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/sticky_pop_ball.png",
    "thumbnail": "/thumbnails/sticky_pop_ball_thumb.png",
    "themeTag": "sticky",
    "behaviorProfile": "goo_ball",
    "searchTags": [
      "sticky",
      "pop",
      "fidget"
    ]
  },
  {
    "id": "wobble_drop",
    "name": "Wobble Drop",
    "rarity": "common",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/wobble_drop.png",
    "thumbnail": "/thumbnails/wobble_drop_thumb.png",
    "themeTag": "wobble",
    "behaviorProfile": "jelly_cube",
    "searchTags": [
      "wobble",
      "drop"
    ]
  },
  {
    "id": "glitter_goo_ball",
    "name": "Glitter Goo Ball",
    "rarity": "rare",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/glitter_goo_ball.png",
    "thumbnail": "/thumbnails/glitter_goo_ball_thumb.png",
    "themeTag": "glitter_goo",
    "behaviorProfile": "goo_ball",
    "searchTags": [
      "glitter",
      "goo",
      "rare"
    ]
  },
  {
    "id": "shockwave_blob",
    "name": "Shockwave Blob",
    "rarity": "rare",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/shockwave_blob.png",
    "thumbnail": "/thumbnails/shockwave_blob_thumb.png",
    "themeTag": "shockwave",
    "behaviorProfile": "goo_ball",
    "searchTags": [
      "shockwave",
      "electric",
      "rare"
    ]
  },
  {
    "id": "frost_gel_cube",
    "name": "Frost Gel Cube",
    "rarity": "rare",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/frost_gel_cube.png",
    "thumbnail": "/thumbnails/frost_gel_cube_thumb.png",
    "themeTag": "frost",
    "behaviorProfile": "jelly_cube",
    "searchTags": [
      "frost",
      "ice",
      "rare"
    ]
  },
  {
    "id": "plasma_goo_ball",
    "name": "Plasma Goo Ball",
    "rarity": "epic",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/plasma_goo_ball.png",
    "thumbnail": "/thumbnails/plasma_goo_ball_thumb.png",
    "themeTag": "plasma",
    "behaviorProfile": "goo_ball",
    "searchTags": [
      "plasma",
      "goo",
      "epic"
    ]
  },
  {
    "id": "aurora_stretch_cube",
    "name": "Aurora Stretch Cube",
    "rarity": "epic",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/aurora_stretch_cube.png",
    "thumbnail": "/thumbnails/aurora_stretch_cube_thumb.png",
    "themeTag": "aurora",
    "behaviorProfile": "stress_ball",
    "searchTags": [
      "aurora",
      "stretch",
      "epic"
    ]
  },
  {
    "id": "cosmic_jelly_pad",
    "name": "Cosmic Jelly Pad",
    "rarity": "epic",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/cosmic_jelly_pad.png",
    "thumbnail": "/thumbnails/cosmic_jelly_pad_thumb.png",
    "themeTag": "cosmic",
    "behaviorProfile": "jelly_cube",
    "searchTags": [
      "cosmic",
      "jelly",
      "epic"
    ]
  },
  {
    "id": "singularity_goo_core",
    "name": "Singularity Goo Core",
    "rarity": "legendary",
    "packId": "goo_fidgets_drop_01",
    "packSlug": "goo-and-fidgets",
    "packName": "Goo & Fidgets",
    "sprite": "/sprites/singularity_goo_core.png",
    "thumbnail": "/thumbnails/singularity_goo_core_thumb.png",
    "themeTag": "singularity",
    "behaviorProfile": "goo_ball",
    "searchTags": [
      "singularity",
      "legendary",
      "legendary"
    ]
  },
  {
    "id": "dumplio",
    "name": "Dumplio",
    "rarity": "common",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/dumplio.png",
    "thumbnail": "/thumbnails/dumplio_thumb.png",
    "themeTag": "viral_food_energy",
    "behaviorProfile": null,
    "searchTags": [
      "squishy",
      "dumpling",
      "asmr",
      "satisfying",
      "food"
    ]
  },
  {
    "id": "jellyzap",
    "name": "JellyZap",
    "rarity": "common",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/jellyzap.png",
    "thumbnail": "/thumbnails/jellyzap_thumb.png",
    "themeTag": "jelly_cube",
    "behaviorProfile": null,
    "searchTags": [
      "jelly",
      "pop",
      "asmr",
      "satisfying"
    ]
  },
  {
    "id": "poppling",
    "name": "Poppling",
    "rarity": "rare",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/poppling.png",
    "thumbnail": "/thumbnails/poppling_thumb.png",
    "themeTag": "soft_dessert",
    "behaviorProfile": null,
    "searchTags": [
      "mochi",
      "squish",
      "relaxing",
      "food"
    ]
  },
  {
    "id": "peach_mochi",
    "name": "Peach Mochi",
    "rarity": "common",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/peach_mochi.png",
    "thumbnail": "/thumbnails/peach_mochi_thumb.png",
    "themeTag": "mochi",
    "behaviorProfile": "mochi",
    "searchTags": [
      "mochi",
      "peach",
      "dessert"
    ]
  },
  {
    "id": "syrup_cube",
    "name": "Syrup Cube",
    "rarity": "common",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/syrup_cube.png",
    "thumbnail": "/thumbnails/syrup_cube_thumb.png",
    "themeTag": "jelly",
    "behaviorProfile": "jelly_cube",
    "searchTags": [
      "syrup",
      "jelly",
      "cube"
    ]
  },
  {
    "id": "cream_puff",
    "name": "Cream Puff",
    "rarity": "common",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/cream_puff.png",
    "thumbnail": "/thumbnails/cream_puff_thumb.png",
    "themeTag": "pastry",
    "behaviorProfile": "dumpling",
    "searchTags": [
      "cream",
      "puff",
      "pastry"
    ]
  },
  {
    "id": "rice_ball_squish",
    "name": "Rice Ball Squish",
    "rarity": "common",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/rice_ball_squish.png",
    "thumbnail": "/thumbnails/rice_ball_squish_thumb.png",
    "themeTag": "onigiri",
    "behaviorProfile": "dumpling",
    "searchTags": [
      "rice",
      "onigiri",
      "food"
    ]
  },
  {
    "id": "marshmallow_puff",
    "name": "Marshmallow Puff",
    "rarity": "common",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/marshmallow_puff.png",
    "thumbnail": "/thumbnails/marshmallow_puff_thumb.png",
    "themeTag": "marshmallow",
    "behaviorProfile": "dumpling",
    "searchTags": [
      "marshmallow",
      "soft"
    ]
  },
  {
    "id": "pudding_pop",
    "name": "Pudding Pop",
    "rarity": "common",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/pudding_pop.png",
    "thumbnail": "/thumbnails/pudding_pop_thumb.png",
    "themeTag": "pudding",
    "behaviorProfile": "jelly_cube",
    "searchTags": [
      "pudding",
      "wobble"
    ]
  },
  {
    "id": "rainbow_jelly_bun",
    "name": "Rainbow Jelly Bun",
    "rarity": "rare",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/rainbow_jelly_bun.png",
    "thumbnail": "/thumbnails/rainbow_jelly_bun_thumb.png",
    "themeTag": "jelly_bun",
    "behaviorProfile": "jelly_cube",
    "searchTags": [
      "rainbow",
      "jelly",
      "rare"
    ]
  },
  {
    "id": "sparkle_mochi",
    "name": "Sparkle Mochi",
    "rarity": "rare",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/sparkle_mochi.png",
    "thumbnail": "/thumbnails/sparkle_mochi_thumb.png",
    "themeTag": "sparkle_mochi",
    "behaviorProfile": "mochi",
    "searchTags": [
      "sparkle",
      "mochi",
      "rare"
    ]
  },
  {
    "id": "golden_syrup_cube",
    "name": "Golden Syrup Cube",
    "rarity": "rare",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/golden_syrup_cube.png",
    "thumbnail": "/thumbnails/golden_syrup_cube_thumb.png",
    "themeTag": "gold_syrup",
    "behaviorProfile": "jelly_cube",
    "searchTags": [
      "gold",
      "syrup",
      "rare"
    ]
  },
  {
    "id": "galaxy_dumpling",
    "name": "Galaxy Dumpling",
    "rarity": "epic",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/galaxy_dumpling.png",
    "thumbnail": "/thumbnails/galaxy_dumpling_thumb.png",
    "themeTag": "galaxy",
    "behaviorProfile": "dumpling",
    "searchTags": [
      "galaxy",
      "dumpling",
      "epic"
    ]
  },
  {
    "id": "crystal_mochi",
    "name": "Crystal Mochi",
    "rarity": "epic",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/crystal_mochi.png",
    "thumbnail": "/thumbnails/crystal_mochi_thumb.png",
    "themeTag": "crystal",
    "behaviorProfile": "mochi",
    "searchTags": [
      "crystal",
      "mochi",
      "epic"
    ]
  },
  {
    "id": "neon_dessert_blob",
    "name": "Neon Dessert Blob",
    "rarity": "epic",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/neon_dessert_blob.png",
    "thumbnail": "/thumbnails/neon_dessert_blob_thumb.png",
    "themeTag": "neon",
    "behaviorProfile": "jelly_cube",
    "searchTags": [
      "neon",
      "jelly",
      "epic"
    ]
  },
  {
    "id": "celestial_dumpling_core",
    "name": "Celestial Dumpling Core",
    "rarity": "legendary",
    "packId": "launch_squishy_foods",
    "packSlug": "squishy-foods",
    "packName": "Squishy Foods",
    "sprite": "/sprites/celestial_dumpling_core.png",
    "thumbnail": "/thumbnails/celestial_dumpling_core_thumb.png",
    "themeTag": "celestial_legendary",
    "behaviorProfile": "dumpling",
    "searchTags": [
      "celestial",
      "legendary",
      "legendary"
    ]
  }
];

export const packs: PackSummary[] = [
  {
    "id": "launch_squishy_foods",
    "slug": "squishy-foods",
    "displayName": "Squishy Foods",
    "blurb": "Cozy cream mochis, glossy jelly cubes, and galaxy dumplings.",
    "accent": "#FF8FB8",
    "accentDark": "#FF6FA5",
    "emoji": "🍱",
    "counts": {
      "common": 8,
      "rare": 4,
      "epic": 3,
      "legendary": 1
    },
    "legendaryName": "Celestial Dumpling Core",
    "totalCount": 16
  },
  {
    "id": "goo_fidgets_drop_01",
    "slug": "goo-and-fidgets",
    "displayName": "Goo & Fidgets",
    "blurb": "Sticky goo balls, stress orbs, and cosmic jelly pads.",
    "accent": "#B6FF5C",
    "accentDark": "#7FE7FF",
    "emoji": "🧪",
    "counts": {
      "common": 8,
      "rare": 4,
      "epic": 3,
      "legendary": 1
    },
    "legendaryName": "Singularity Goo Core",
    "totalCount": 16
  },
  {
    "id": "creepy_cute_pack_01",
    "slug": "creepy-cute-creatures",
    "displayName": "Creepy-Cute Creatures",
    "blurb": "Bunnies, bats, and glow ghosts — creepy, cute, never scary.",
    "accent": "#C98BFF",
    "accentDark": "#8040D8",
    "emoji": "👻",
    "counts": {
      "common": 8,
      "rare": 4,
      "epic": 3,
      "legendary": 1
    },
    "legendaryName": "Mythic Plush Familiar",
    "totalCount": 16
  }
];
